name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.3

  # Charts
  fl_chart: ^0.69.0

  # QR Scanner
  mobile_scanner: ^5.2.3

  # Image Picker
  image_picker: ^1.1.2

  # Networking
  dio: ^5.11.0

  # Secure Storage
  flutter_secure_storage: ^10.3.1

  # OTP Input
  pinput: ^6.0.2

  # Animations
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3

  # Loading Skeleton
  shimmer: ^3.0.0

  # Internet Connectivity
  connectivity_plus: ^7.3.1

  # PDF Receipt
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.6
  share_plus: ^13.3.0
  qr_flutter: ^4.1.0
  open_filex: ^4.7.0
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/