import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';

class ReceiptPdfService {
  ReceiptPdfService._();

  static final ReceiptPdfService instance = ReceiptPdfService._();

  Future<File> generateReceipt({
    required String receiverName,
    required String upiId,
    required String amount,
    required String transactionId,
  }) async {
    final pdf = pw.Document();

    final now = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Center(
            child: pw.Column(
              children: [
                pw.Text(
                  "PayFlow",
                  style: pw.TextStyle(
                    fontSize: 30,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue,
                  ),
                ),

                pw.SizedBox(height: 8),

                pw.Text(
                  "Payment Receipt",
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),

                pw.Divider(),

                pw.SizedBox(height: 20),

                pw.Text(
                  "PAYMENT SUCCESSFUL",
                  style: pw.TextStyle(
                    color: PdfColors.green,
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 18,
                  ),
                ),

                pw.SizedBox(height: 20),

                pw.Text(
                  "₹$amount",
                  style: pw.TextStyle(
                    fontSize: 36,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),

                pw.SizedBox(height: 30),
              ],
            ),
          ),

          _row("Receiver", receiverName),
          _row("UPI ID", upiId),
          _row("Transaction ID", transactionId),
          _row("Status", "SUCCESS"),
          _row("Payment Method", "PayFlow Wallet"),
          _row("Date", "${now.day}/${now.month}/${now.year}"),
          _row("Time", "${now.hour}:${now.minute.toString().padLeft(2, '0')}"),

          pw.SizedBox(height: 30),

          pw.Center(
            child: pw.BarcodeWidget(
              barcode: pw.Barcode.qrCode(),
              data: transactionId,
              width: 140,
              height: 140,
            ),
          ),

          pw.SizedBox(height: 40),

          pw.Center(
            child: pw.Text(
              "Generated by PayFlow",
              style: const pw.TextStyle(color: PdfColors.grey),
            ),
          ),
        ],
      ),
    );

    final dir = await getApplicationDocumentsDirectory();

    final file = File("${dir.path}/Receipt_$transactionId.pdf");

    await file.writeAsBytes(await pdf.save());

    return file;
  }

  Future<void> printReceipt({
    required String receiverName,
    required String upiId,
    required String amount,
    required String transactionId,
  }) async {
    final file = await generateReceipt(
      receiverName: receiverName,
      upiId: upiId,
      amount: amount,
      transactionId: transactionId,
    );

    await Printing.layoutPdf(onLayout: (_) => file.readAsBytes());
  }

  Future<void> shareReceipt({
    required String receiverName,
    required String upiId,
    required String amount,
    required String transactionId,
  }) async {
    final file = await generateReceipt(
      receiverName: receiverName,
      upiId: upiId,
      amount: amount,
      transactionId: transactionId,
    );

    await Share.shareXFiles([
      XFile(file.path),
    ], text: "PayFlow Payment Receipt");
  }

  Future<File> saveReceipt({
    required String receiverName,
    required String upiId,
    required String amount,
    required String transactionId,
  }) async {
    return generateReceipt(
      receiverName: receiverName,
      upiId: upiId,
      amount: amount,
      transactionId: transactionId,
    );
  }

  static pw.Widget _row(String title, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 6),
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Text(
              title,
              style: const pw.TextStyle(color: PdfColors.grey),
            ),
          ),
          pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
